-- Editable USPS shipping rates (admin dashboard) + is_admin flag.

alter table public.users add column if not exists is_admin boolean not null default false;

comment on column public.users.is_admin is 'Can edit platform settings such as shipping rates.';

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select u.is_admin from public.users u where u.id = (select auth.uid())::text),
    false
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- Do not let users flip their own admin flag via profile update.
create or replace function public.protect_is_admin()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.is_admin is distinct from old.is_admin then
    if not public.is_admin() then
      new.is_admin := old.is_admin;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists users_protect_is_admin on public.users;
create trigger users_protect_is_admin
before update on public.users
for each row execute procedure public.protect_is_admin();

create table if not exists public.shipping_rates (
  id          bigint generated by default as identity primary key,
  max_value   numeric(12,2) not null,
  label       text not null,
  price       numeric(12,2) not null,
  insurance   numeric(12,2) not null default 0,
  sort_order  integer not null default 0,
  updated_at  timestamptz not null default now()
);

comment on table public.shipping_rates is 'Buyer shipping charge tiers by listing value. Edited in Admin Dashboard.';

alter table public.shipping_rates enable row level security;

drop policy if exists "shipping_rates_select_authenticated" on public.shipping_rates;
create policy "shipping_rates_select_authenticated"
on public.shipping_rates
for select
to authenticated
using (true);

drop policy if exists "shipping_rates_write_admin" on public.shipping_rates;
create policy "shipping_rates_insert_admin"
on public.shipping_rates
for insert
to authenticated
with check (public.is_admin());

create policy "shipping_rates_update_admin"
on public.shipping_rates
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "shipping_rates_delete_admin"
on public.shipping_rates
for delete
to authenticated
using (public.is_admin());

grant usage, select on sequence public.shipping_rates_id_seq to authenticated;

insert into public.shipping_rates (max_value, label, price, insurance, sort_order)
select * from (values
  (50::numeric,    'Small Flat Rate Box'::text,  9.45::numeric,  0::numeric,    1),
  (100::numeric,   'Medium Flat Rate Box',      14.65,           0,             2),
  (500::numeric,   'Large Flat Rate Box',       19.95,           2.75,          3),
  (99999::numeric, 'Large Flat Rate Box',       19.95,           4.95,          4)
) as v(max_value, label, price, insurance, sort_order)
where not exists (select 1 from public.shipping_rates);

-- Promote known operator accounts if they already exist.
update public.users
set is_admin = true
where lower(username) in ('dannyinhand', 'danny', 'dannyweinstein')
  and is_admin is distinct from true;
